ecomm/ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('toko.urls', namespace='toko')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm/toko/urls.py
from django.urls import path
from . import views

app_name = 'toko'

urlpatterns = [
     path('', views.HomeListView.as_view(), name='home-produk-list'),
     path('product/<slug>/', views.ProductDetailView.as_view(), name='produk-detail'),
     path('checkout/', views.CheckoutView.as_view(), name='checkout'),
     path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
     path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
     path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
     path('payment/<payment_method>', views.PaymentView.as_view(), name='payment'),
     path('paypal-return/', views.paypal_return, name='paypal-return'),
     path('paypal-cancel/', views.paypal_cancel, name='paypal-cancel'),
]

ecomm/toko/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

PILIHAN_KATEGORI = (
    ('S', 'Sandal'),
    ('SK', 'Sneakers'),
    ('FL', 'Flatshoes'),
    ('B', 'Boots')
)

PILIHAN_LABEL = (
    ('NEW', 'primary'),
    ('SALE', 'info'),
    ('BEST', 'danger'),
)

PILIHAN_PEMBAYARAN = (
    ('P', 'Paypal'),
    ('S', 'Stripe'),
)

User = get_user_model()

class ProdukItem(models.Model):
    nama_produk = models.CharField(max_length=100)
    harga = models.FloatField()
    harga_diskon = models.FloatField(blank=True, null=True)
    slug = models.SlugField(unique=True)
    deskripsi = models.TextField()
    gambar = models.ImageField(upload_to='product_pics')
    label = models.CharField(choices=PILIHAN_LABEL, max_length=4)
    kategori = models.CharField(choices=PILIHAN_KATEGORI, max_length=2)

    def __str__(self):
        return f"{self.nama_produk} - ${self.harga}"

    def get_absolute_url(self):
        return reverse("toko:produk-detail", kwargs={
            "slug": self.slug
            })

    def get_add_to_cart_url(self):
        return reverse("toko:add-to-cart", kwargs={
            "slug": self.slug
            })
    
    def get_remove_from_cart_url(self):
        return reverse("toko:remove-from-cart", kwargs={
            "slug": self.slug
            })
    
class OrderProdukItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    produk_item = models.ForeignKey(ProdukItem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.produk_item.nama_produk}"

    def get_total_harga_item(self):
        return self.quantity * self.produk_item.harga
    
    def get_total_harga_diskon_item(self):
        return self.quantity * self.produk_item.harga_diskon

    def get_total_hemat_item(self):
        return self.get_total_harga_item() - self.get_total_harga_diskon_item()
    
    def get_total_item_keseluruan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_harga_diskon_item()
        return self.get_total_harga_item()
    
    def get_total_hemat_keseluruhan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_hemat_item()
        return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    produk_items = models.ManyToManyField(OrderProdukItem)
    tanggal_mulai = models.DateTimeField(auto_now_add=True)
    tanggal_order = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    alamat_pengiriman = models.ForeignKey('AlamatPengiriman', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

     
    def get_total_harga_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_item_keseluruan()
        return total
    
    def get_total_hemat_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_hemat_keseluruhan()
        return total

class AlamatPengiriman(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    alamat_1 = models.CharField(max_length=100)
    alamat_2 = models.CharField(max_length=100)
    negara = models.CharField(max_length=100)
    kode_pos = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username} - {self.alamat_1}"

    class Meta:
        verbose_name_plural = 'AlamatPengiriman'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_option = models.CharField(choices=PILIHAN_PEMBAYARAN, max_length=1)
    charge_id = models.CharField(max_length=50)

    def __self__(self):
        return self.user.username
    
    def __str__(self):
        return f"{self.user.username} - {self.payment_option} - {self.amount}"
    
    class Meta:
        verbose_name_plural = 'Payment'

ecomm/ecomm/templates/base.html
{% load static %}

<!DOCTYPE html>
  <html lang="en-US" dir="ltr">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>e-commerce {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <link rel="icon" href="{% static 'img/mdb-favicon.ico' %}" type="image/x-icon" />   

    <link rel="stylesheet" href="{% static 'redesign/assets/css/theme.css' %}" />    
  </head>

  <body>
    
    {% include 'navbar.html' %}
 

    <div class="mt-5 pt-4">
      {% if messages %}
          {% for message in messages %}
          <div class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissable">
              <strong>{{ message }}</strong>
            </div>
          </div>
          {% endfor %}
      {% endif %}
    </div>

    {% block content %}
    {% endblock content %}
    
    {% include 'footer.html' %}
  
    {% include 'scripts.html' %}

    {% block scripts %}
    {% endblock scripts %}

  </body>
</html>

ecomm/ecomm/templates/home-OLD.html
{% extends 'base.html' %}

{% block content %}

{% include 'carousel.html' %}

<!--Main layout-->
<main>
    <div class="container">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #607D8B">
            <!-- Container wrapper -->
            <div class="container-fluid">

                <!-- Navbar brand -->
                <a class="navbar-brand" href="#">Categories: asd</a>

                <!-- Toggle button -->
                <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent2"
                        aria-controls="navbarSupportedContent2"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <!-- Link -->
                        <li class="nav-item acitve">
                            <a class="nav-link text-white" href="#">All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Sport wears</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Outwears</a>
                        </li>

                    </ul>

                    <!-- Search -->
                    <form class="w-auto py-1" style="max-width: 12rem">
                        <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
                    </form>

                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

        <!-- Products -->
        <section>
            <div class="text-center">
              <div class="row">
                
                {% for pItem in object_list %}
                <div class="col-lg-3 col-md-6 mb-4">
                  <div class="card">
                    <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                      data-mdb-ripple-color="light">
                      <img src="{{ pItem.gambar.url }}"
                        class="w-100" />
                      <a href="{{ pItem.get_absolute_url }}"> 
                        <div class="mask">
                          <div class="d-flex justify-content-start align-items-end h-100">
                            <h5><span class="badge bg-{{ pItem.get_label_display }} ms-2">{{ pItem.label }}</span></h5>
                          </div>
                        </div>
                        <div class="hover-overlay">
                          <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                        </div>
                      </a>
                    </div>
                    <div class="card-body">
                      <a href="{{ pItem.get_absolute_url }}" class="text-reset">
                        <h5 class="card-title mb-2">{{ pItem.nama_produk }}</h5>
                      </a>
                      <a href="" class="text-reset ">
                        <p>{{ pItem.get_kategori_display }}</p>
                      </a>
                      <h6 class="mb-3 price">${% if pItem.harga_diskon %}{{ pItem.harga_diskon }}{% else %}{{ pItem.harga }}{% endif %}</h6>
                    </div>
                  </div>
                </div>
                {% empty %}
                  <p>Data Produk belum tersedia</p>
                {% endfor %}

              </div>
            </div>
          </section>
        <!-- End Products -->

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                <li class="page-item">
                  {% if page_obj.has_previous %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                  {% endif %}
                </li>
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                <li class="page-item">
                  {% if page_obj.has_next %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                  {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
        <!-- Pagination -->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

ecomm/ecomm/templates/home.html
{% extends 'base.html' %}

{% block content %}

<section class="py-5 overflow-hidden bg-primary" id="home">
  <div class="container">
    <div class="row flex-center">
      <div class="col-md-5 col-lg-6 order-0 order-md-1 mt-8 mt-md-0"><a class="img-landing-banner" href="#!"><img class="img-fluid" src="media/redesign/assets/img/gallery/bg.png" alt="hero-header" /></a></div>
      <div class="col-md-7 col-lg-6 py-8 text-md-start text-center">
        <h1 class="display-1 fs-md-5 fs-lg-6 fs-xl-8 text-light">YOUR SHOES</h1>
        <h1 class="text-800 mb-5 fs-4">Langkah dengan gaya <br class="d-none d-xxl-block" />jelajahi dunia dengan sepatu terbaik Anda</h1>
      </div>
    </div>
  </div>
</section>

<!-- List Produk -->
<section id="testimonial">
  <div class="container">
    <div class="row mb-3">
      <div class="col-12">
        <div class="row input-group-icon mb-2">
          <div class="col-10"><i class="fas fa-search input-box-icon text-500 ms-3"></i>
            <input class="form-control input-box border-2" type="email" placeholder="Cari produk keinginan anda" aria-label="email" />
          </div>
          <div class="col-2">
            <button class="btn btn-secondary" type="submit">Cari Produk</button>
          </div>
        </div>
      </div>
    </div>

    <div class="row h-100 mb-5">
      <div class="col-12 justify-content-center text-center">
        <a class="btn btn-md btn-danger" href="#">Paling Laris</a>
        <a class="btn btn-md btn-dark" href="#">Fashion Anak</a>
        <a class="btn btn-md btn-primary" href="#">Fashion Pria</a>
      </div>
    </div>

    <div class="row h-100">
      <div class="col-lg-7 mx-auto text-center mb-6">
        <h5 class="fw-bold fs-3 fs-lg-5 lh-sm mb-3">Produk Terbaru</h5>
      </div>
    </div>
    <div class="row gx-2">
      {% for pItem in object_list %}
      <div class="col-sm-6 col-md-3 col-lg-3 mb-5">
        <div class="card card-span h-100 text-white rounded-3">
          <a href="{{ pItem.get_absolute_url }}"><img class="img-fluid rounded-3" style="height: 300px; width: 100%;" src="{{ pItem.gambar.url }}" alt="{{ pItem.nama_produk }}" /></a>
          
          <div class="card-body ps-0">
            <div class="d-flex align-items-center mb-3">
              <div class="flex-1 ms-3">
                <a href="#"><span class="badge bg-danger mb-2"> New </span></a> 
                <a href="#"><span class="badge bg-primary mb-2"> {{ pItem.get_kategori_display }}</span></a>
                
                <a href="{{ pItem.get_absolute_url }}" class="text-reset">
                  <h5 class="card-title mb-2">{{ pItem.nama_produk }}</h5>
                </a>

                <p style="color: #000">Deskripsi : {{ pItem.deskripsi }}</p>
              </div>
            </div>
            <div class="text-center">
              <span class="badge bg-soft-danger p-2"><span class="fw-bold fs-1 text-danger">{% if pItem.harga_diskon %} <strike>Rp. {{ pItem.harga }}</strike> {% endif %}</span></span>
              <span class="badge bg-soft-secondary p-2 mt-2"><span class="fw-bold fs-1 text-secondary">Rp. {% if pItem.harga_diskon %} {{ pItem.harga_diskon }}{% else %}{{ pItem.harga }}{% endif %}</span></span>
            </div>
            <div class="d-grid gap-2 mt-3"><a class="btn btn-lg btn-danger" href="/add-to-cart/{{ pItem.slug }}" role="button" style="min-width: none;">Order now</a></div>
          </div>
        </div>
      </div>
      {% empty %}
        <p>Data Produk belum tersedia</p>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

ecomm/ecomm/templates/navbar-OLD.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">    
        <!-- Toggle button -->
        <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <i class="fas fa-bars"></i>
        </button>
    
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">      
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-sm-0" href="#">
            <img
            src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
            height="20"
            alt="MDB Logo"
            loading="lazy"
            />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
            <a class="nav-link " href="/">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'toko:checkout' %}">Checkout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">Kontak</a>
                </li>
        </ul>
        <!-- Left links -->      
        </div>
        <!-- Collapsible wrapper -->
        
        <!-- Right elements -->
        <div class="d-flex align-items-center">
            {% if request.user.is_authenticated %}
                <!-- Icon -->
                <a class="nav-link me-3" href="{% url 'toko:order-summary' %}">
                    <i class="fas fa-shopping-cart"></i>
                    <span class="badge rounded-pill badge-notification bg-danger">{{ request.user|total_produk_dikeranjang }}</span>
                </a>
                <a class="nav-link me-3" href="{% url 'account_logout' %}">
                    <i class="fas fa-right-from-bracket"></i>
                </a>
            {% else %}
                <a class="nav-link me-3" href="{% url 'account_login' %}">
                <i class="fas fa-right-to-bracket"></i>
            {% endif %}
        </div> 
        <!-- Right elements -->
        
    </div>
    <!-- Container wrapper -->
</nav>
    <!-- Navbar -->

ecomm/ecomm/templates/navbar.html
{% load cart_template_tags %}
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" data-navbar-on-scroll="data-navbar-on-scroll" style="padding-top: 20px;">
    <div class="container"><a class="navbar-brand d-inline-flex" href="/"><span class="text-1000 fs-3 fw-bold ms-2 text-gradient">WIT Shop</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"> </span></button>
        <div class="collapse navbar-collapse border-top border-lg-0 my-2 mt-lg-0" id="navbarSupportedContent">
            <div class="mx-auto pt-5 pt-lg-0 d-block d-lg-none d-xl-block">
                <p class="mb-0 fw-bold text-lg-center">Deliver to: <i class="fas fa-map-marker-alt text-warning mx-2"></i><span class="fw-normal">Current Location </span><span>Jakarta , Indonesia</span></p>
            </div>
        </div>
        
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
                <a class="nav-link " href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'toko:checkout' %}">Checkout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/">Kontak</a>
            </li>
        </ul>

        <!-- Right elements -->
        <div class="d-flex align-items-center">
            {% if request.user.is_authenticated %}
                <!-- Icon -->
                <a class="nav-link me-3" href="{% url 'toko:order-summary' %}">
                    <i class="fas fa-shopping-cart"></i>
                    <span class="badge rounded-pill badge-notification bg-danger">{{ request.user|total_produk_dikeranjang }}</span>
                </a>
                <a class="nav-link me-3" href="{% url 'account_logout' %}">
                    <i class="fas fa-right-from-bracket"></i>
                </a>
            {% else %}
                <a class="nav-link me-3" href="{% url 'account_login' %}">
                <i class="fas fa-right-to-bracket"></i>
            {% endif %}
        </div> 
        <!-- Right elements -->
    </div>
</nav>
<i class="fas fa-motorcycle me-2"></i>

ecomm/ecomm/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 mt-4 mb-4">
            <h1 class="text-center">Order Summary</h1>
        </div>
    </div>
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
        <tr>
            <th>#</th>
            <th>Nama Produk</th>
            <th>Harga</th>
            <th>Quantity</th>
            <th>Total Harga</th>
        </tr>
        </thead>
        <tbody>
            {% for pItem in keranjang.produk_items.all %}
            <tr>
                <td scope="row">
                    {{ forloop.counter }}
                </td>
                <td>
                    <a href="{% url 'toko:produk-detail' pItem.produk_item.slug %}">
                        <div class="d-flex align-items-center">
                            <img
                                src="{{ pItem.produk_item.gambar.url }}"
                                alt=""
                                style="width: 45px; height: 45px"
                                class="rounded-circle"
                                />
                            <div class="ms-3">
                            <p class="fw-bold mb-1">{{ pItem.produk_item.nama_produk }}</p>
                            <p class="text-muted mb-0"> {{ pItem.produk_item.deskripsi|truncatewords:10 }}</p>
                            </div>
                        </div>
                    </a>
                </td>
                <td>
                    <div>$
                        {% if pItem.produk_item.harga_diskon %}
                        {{ pItem.produk_item.harga_diskon }}
                        {% else %}
                        {{ pItem.produk_item.harga }}
                        {% endif %}
                    </div>
                </td>
                <td>{{ pItem.quantity }}</td>
                <td>                
                    {% if pItem.produk_item.harga_diskon %}
                    ${{ pItem.get_total_harga_diskon_item }}
                    <span class="badge badge-danger rounded-pill d-inline">Hemat ${{ pItem.get_total_hemat_item }}</span>
                    {% else %}
                    ${{ pItem.get_total_harga_item }}
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan='5'>Keranjang kosong</td>
            </tr>
            <tr>
                <td colspan="5">
                <a class="btn btn-primary float-end" href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endfor %}

            {% if keranjang.get_total_harga_order %}
            <tr>
                <td colspan="4"><b>Total Belanja</b></td>
                <td><b>${{ keranjang.get_total_harga_order }}</b>
                    {% if keranjang.get_total_hemat_order %}
                    <span class="badge badge-danger">Hemat ${{ keranjang.get_total_hemat_order }}</span>
                    {% endif %}
                </td>
            </tr>

            <tr>
                <td colspan="5">
                <a class='btn btn-info float-end ml-2' href="{% url 'toko:checkout' %}">Checkout</a>
                <a class='btn btn-danger' href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endif %}
        </tbody>
  </table>
</div>
{% endblock content %}

ecomm/ecomm/templates/payment.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="d-flex justify-content-center">
    <div class="row justify-content-center">
      <div class="col pt-5 pb-5">
        <p>Total belanjaan kamu : <strong>${{ order.get_total_harga_order }}</strong></p>
        <br />
        {% if is_paypal %}
        <div>{{ paypalform.render }}</div>
        {% else %}
        <div>Pembayaran Strip belum diaktifkan gunakan Paypal</div>
        <a href="{% url 'toko:payment' 'paypal' %}"><div class="btn btn-info">Paypal</div></a>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

ecomm/ecomm/templates/product_detail.html
{% extends 'base.html' %}

{% block content%}

<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <img src="{{ object.gambar.url }}" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge bg-dark me-1">{{ object.get_kategori_display }}</span>
                        </a>
                        {% if object.label == 'NEW' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">New</span>
                        </a>
                        {% elif object.label == 'SALE' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Sale</span>
                        </a>
                        {% else %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Bestseller</span>
                        </a>
                        {% endif %}
                    </div>

                    <p class="lead">
                        {% if object.harga_diskon %}
                        <span class="me-1">
                            <del>${{ object.harga }}</del>
                        </span>
                        <span>${{ object.harga_diskon }}</span>
                        {% else %}
                        <span>${{ object.harga }}</span>
                        {% endif %}
                    </p>

                    <strong><p style="font-size: 20px;">Deskripsi</p></strong>

                    <p>{{ object.deskripsi }}</p>
                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary ms-1">
                        Tambah ke keranjang
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger ms-1" >
                        Kurangi keranjang
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-md-6 text-center">
                <h4 class="my-4 h4">Additional information</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
{% endblock content%}

ecomm/ecomm/templates/scripts-OLD.html
{% load static %}

<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>